---
# All keys must start with a :
# TODO: make this not terrible

:basic_auth:
  :username: admin
  :password: admin

:mongodb_service:
  :host: localhost
  :port: 27017

:catalog:
  :services:
  - :id: 'ae6c4cd4-90cd-40fc-a677-8d3b9a06f8e4'
    :name: 'mongodb'
    :description: 'MongoDB for everyone!'
    :bindable: true
    :plans:
    - :id: '5d5d6cbd-ab1f-4f28-84e7-a994446ed910'
      :name: 'free'
      :description: 'free-tier MongoDB.'
